name: Using public custom actions

on:
  workflow_dispatch:

jobs:
  custom_js_action_job:
    runs-on: ubuntu-latest
    name: Custom JS Action demo
    steps:
    - name: First JS action step
      id: myjsaction
      uses: harukine/actions-custom-action@v1
      with:
        name-of-you: 'TestName'
    # Use the output from the `myjsaction` step
    - name: Get the output message time
      run: echo "The time was ${{ steps.myjsaction.outputs.time }}"
